environment:
  nodejs_version: "8"
  TWINE_USERNAME: benfred
  # Note: TWINE_PASSWORD is set in Appveyor settings
  matrix:
    # Nightly 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
      CIBW_SKIP: "*win32* cp27-* cp33-* cp34-* cp35-*"
      CIBW_BEFORE_BUILD: pip install setuptools-rust

# from: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - pip install cibuildwheel==0.9.1 setuptools_rust
  - rustc -vV
  - cargo -vV
  - node --version
  - npm --version
  - npm --prefix src\web_viewer\visualizations install

build_script:
  - npm --prefix src\web_viewer\visualizations run build:release
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl
    )

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

deploy:
  auth_token:
    secure: EMR1b8dxTTfdBx9uiUFTg1EG6Gzs9np7Szb1bETvEi10v8N+VKHj9PCNNCUZGpmC
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub
