[package]
name = "py-spy"
version = "0.4.0-dev0"
authors = ["Ben Frederickson <github@benfrederickson.com>"]
repository = "https://github.com/benfred/py-spy"
homepage = "https://github.com/benfred/py-spy"
description = "Sampling profiler for Python programs "
readme = "README.md"
exclude = ["images/*", "test_programs/*"]
license = "MIT"
build="build.rs"
edition = "2018"

[dependencies]
clap = {version="2", features=["wrap_help"]}
console = "0.9"
ctrlc = "3"
indicatif = "0.14"
env_logger = "0.7"
failure = "0.1.5"
goblin = "0.1.3"
handlebars = {version="3", optional=true}
inferno = "0.9.1"
lazy_static = "1.1.0"
libc = "0.2.34"
log = "0.4"
lru = "0.4"
regex = "1"
tempfile = "3.0.3"
proc-maps = "0.1.6"
rouille = {version="2.2.0", optional=true}
rust-embed = {version="5.5", features=["interpolate-folder-path"], optional=true}
mime_guess = {version="1.8.6", optional=true}
memmap = "0.7.0"
cpp_demangle = "0.3"
serde = {version="1.0", features=["rc"]}
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.7"
rand_distr = "0.2"
remoteprocess = {version="0.3.4", features=["unwind"]}

[target.'cfg(unix)'.dependencies]
termios = "0.3.1"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winbase", "consoleapi", "wincon", "handleapi", "timeapi", "processenv" ]}

[profile.release]
lto = true

[features]
default = ["serve"]
serve = ["handlebars", "rouille", "rust-embed", "mime_guess"]
